version: "{build}"
os: Visual Studio 2015
environment:
  GYP_MSVS_VERSION: "2015"
install:
  - cd ..
  - git clone --depth=1 --branch=1.8-dev --recursive https://github.com/alliedmodders/sourcemod sourcemod-1.8
  - git clone --depth=1 --branch=master https://github.com/alliedmodders/ambuild
  - cd ambuild
  - C:\python27\python.exe setup.py install
  - cd %APPVEYOR_BUILD_FOLDER%
  - '"%VS140COMNTOOLS%\vsvars32.bat"'
  - breakpad.bat
  - set PATH=%PATH%;%CD%\breakpad\src\src\tools\windows\dump_syms\Release
build_script:
  - mkdir build
  - cd build
  - C:\python27\python.exe ..\configure.py --enable-optimize
  - C:\python27\python.exe build.py
test: off
on_success:
  - C:\python27\python.exe ..\upload.py
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
